title: AICL 2020 
description: Virtual Camp Podcast Mystery Zombie Theatre
theme: minima

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - "**README.md"

header_pages:
  - _pages/camp-map.md

collections:
  # Ideally we would use collections for slides but this
  # breaks reveal.js markdown processing because of issue:
  # https://github.com/jekyll/jekyll/issues/6209
  # slides:
  #   output: true
  #   permalink: /:collection/:path/
  
  worksheets:
    output: true
    permalink: /:collection/:path/
